### ISSUE TITLE
How to deploy updated docker container without stopping old container

### ISSUE THREAD

**Issue by rajasekaran07** [cloudbees/jenkins-scripts#40]
Hi Team,

We are following Jenkins CICD pipeline flow for our AWS ECS container based applications. My CICD will start whether we updated any configuration in old container, Task definition, Service or any docker service. That will build new docker images based on the changes and uploaded in AWS ECR than it will deploy in our ECS cluster.

While we deploying we stopped old containers and start with new one, Since we cant use same docker name and same port for updated container.

Kindly someone can suggest how to deploy updated container without downtime.

Regards,
Raja

**Comment by schottsfired** [comment]
Hi @rajasekaran07,
It sounds like the Blue-Green Deployment pattern fits your use-case.

I would recommend checking out this blog post:
https://technologyconversations.com/2016/02/08/blue-green-deployment/

Unfortunately I don't have a "one size fits all" script to pass along, but let me know if the literature above is helpful.

Best,
David

**Comment by rajasekaran07** [comment]
@schottsfired Thanks for your valuable input. I would like to know is there any other method available for zero downtime while deploying new micro service.

Regards,
Raja

**Comment by schottsfired** [comment]
@rajasekaran07 it seems like there are interesting things going on in the "Docker native, dynamic proxy" space, check out [Traefik](https://github.com/containous/traefik) and [Docker Flow Proxy](https://github.com/vfarcic/docker-flow-proxy). I poked at the latter a few weeks ago, it's very convenient with e.g. Docker Swarm based setups.

**Comment by rajasekaran07** [comment]
@schottsfired thanks for the information we already implemented with blue-green deployment.

-Raja

**Comment by allanfreitas** [comment]
> @schottsfired thanks for the information we already implemented with blue-green deployment.
> 
> -Raja

Can you share?
